### PR TITLE
chore: update highlight code to include tabindex

### PR DESCRIPTION
**Pull request by davidma415**
https://user-images.githubusercontent.com/40131297/142051082-fb8691da-ce85-4d08-8ea6-2ce8e6aa33e7.mov

### Description
Add tabindex to the highlight code component

### My PR contains... 

- [ ] No code changes (`src/` is unmodified: changes to documentation, CI, metadata, etc.)
- [ ] Dependency changes (any modification to dependencies in `package.json`)
- [ ] Bug fixes (non-breaking change which fixes an issue)
- [ ] Improvements (misc. changes to existing features)
- [ ] Features (non-breaking change which adds functionality)

### My changes...
- [ ] are breaking changes to a public API (config options, System API, major UI change, etc).
- [ ] are breaking changes to a private API (Redux, component props, utility functions, etc.).
- [ ] are breaking changes to a developer API (npm script behavior changes, new dev system dependencies, etc).
- [ ] are not breaking changes.

### Documentation
- [ ] My changes do not require a change to the project documentation.
- [ ] My changes require a change to the project documentation.
- [ ] If yes to above: I have updated the documentation accordingly.

### Automated tests
- [ ] My changes can not or do not need to be tested.
- [ ] My changes can and should be tested by unit and/or integration tests.
- [ ] If yes to above: I have added tests to cover my changes.
- [ ] If yes to above: I have taken care to cover edge cases in my tests.
- [ ] All new and existing tests passed.

### CODE REVIEW

**Comment by codelemur** [comment]
So a few things:

1. I'm having a hard time producing the bug in the first place.
2.  the `pre` tag you've edited isn't the one that the screenshot in the ticket is highlighting (I'm not sure which `pre` is causing the issue, since I can't get the reporter to log it, so you very well might be fixing the right one and I'm just not clear from ticket). (blob:https://konghq.atlassian.net/7586ccf8-a642-49b0-9f69-9d7b812fc062#media-blob-url=true&id=e3ec2d7f-40bb-499c-93bd-1fecb0948535&contextId=35276&collection=)
3.  tab index is a good quick solution, but want to make sure it doesn't ruin the keyboard navigation flow, so if you could record a quick walkthrough confirming how the tab order is affected, that'd be super helpful. From going through it manually, it seems okay as far as I can tell, just for future tab-order modification stuff.

**Review by codelemur — CHANGES_REQUESTED** [review]
Just need a little more info before I can verify.

**Comment by davidma415** [comment]
@codelemur updated the description with the a video describing the issue + proposed solution with the changes

**Review by codelemur — APPROVED** [review]
Video helped, thanks a lot!

**Pull request merged**
